Reimplemented pathoscope.run in rust
virtool/workflow-pathoscope pull request #42
Opened 2023-01-18 21:08 UTC by SnickerDoodlePop

Implimented many of the pathoscope.py functions in rust with the goal of improving runtime performance; added a binding for expectation_maximization::run (.rs) using pyo3 and maturin.

Output data of virtool_expectation_maximization::run (.whl) is not identical to the previous version of pathoscope.run. Data is minutely different in the last 2-3 floating point digits; the output matrix has records in different indices, but fields still correspond to the correct record.

2023-01-19 20:14 UTC, igboyes requested changes
Thanks. I am excited to see this perform in production.

# Housekeeping

* Clean-up various variants of `rewrite.sam`. Make sure there are no unused test files.
* Eschew non-standard formatting. Use automated formatting provided by `rustfmt`.
* Fix inconsistencies in whitespace. `rustfmt` will deal with this for you.
* Is there a benefit to declaring `mod` with only a single function in it?
* Is there any unused Python code remaining in `pathoscope.py`? Please remove if so.

# Tests
For the most part, I don't think the Rust unit tests are thorough enough to guarantee there has been no regression as a result of future changes.

We should be verifying that given inputs result in exactly the same output. The current assertions only touch part of the output where we should be verifying the entire output. This will provide a short feedback loop to support fearless refactors of these functions in the future.

# Safety
I think it is unlikely that you need to use `unsafe` for this work. If the code needs to start deviating from the patterns from the old Python module in order for it to have safety guarantees, so be it.

2023-01-19 20:14 UTC, igboyes commented on src/lib.rs
> +    ///produces the SAM matrix given a path to a .SAM file
```suggestion
```

2023-01-19 20:14 UTC, igboyes commented on src/lib.rs
> +///Wrapper for the buildMatrix function and adjacent code
```suggestion
```

2023-01-19 20:32 UTC, SnickerDoodlePop commented on tests/test_pathoscope.py
> +@pytest.mark.parametrize("max_iter", [5])
oops, this wasn't supposed to be committed

2023-01-20 23:18 UTC, igboyes approved these changes

2023-01-23 19:44 UTC, merged